# MUSIC_DIRECTORY: "/D/Downloads/Music"

# st SourceCodeProMedium
# ADDITIONAL_PADDING_Y : 18
# ADDITIONAL_PADDING_X : 11

# IMAGE_WIDTH_EXTRA_X  : -0.7
# IMAGE_WIDTH_EXTRA_Y  : -2.6

# ------------------------------------

# alacritty
# ADDITIONAL_PADDING_X : 12
# ADDITIONAL_PADDING_Y : 4

# ------------------------------------

# URXVT
# ADDITIONAL_PADDING_X : 10
# ADDITIONAL_PADDING_Y : 15

# ------------------------------------

# Jetbrains mono nerd font regular st
# ADDITIONAL_PADDING_Y : 16
# ADDITIONAL_PADDING_X : 11

# IMAGE_WIDTH_EXTRA_X  : -0.7
# IMAGE_WIDTH_EXTRA_Y  : -2.4

# Sauce Code Pro nerd font regular st
ADDITIONAL_PADDING_Y : 17
ADDITIONAL_PADDING_X : 11

IMAGE_WIDTH_EXTRA_X  : -0.6
IMAGE_WIDTH_EXTRA_Y  : -2.5

MPD_PORT : "6600"
# NETWORK_TYPE : "unix"
# NETWORK_ADDRESS: "~/.mpd/socket"

DEFAULT_IMAGE_PATH: "~/.config/gomp/default.jpg"

GET_COVER_ART_FROM_LAST_FM : "TRUE"
LASTFM_API_KEY: "d32bad56539caa9a826a73015ea72563"
LASTFM_API_SECRET: "e2e04d8eeb5cd3aa5a98932b71c10c07"
LASTFM_AUTO_CORRECT: 1

decreaseVolume :
  - "<"
increaseVolume :
  - ">"
showChildrenContent :
  - "ENTER"

SEEK_OFFSET : 5

CACHE_DIR : "~/.config/gomp/cache"
