[colors]
draw_bold_text_with_bright_colors = false

[colors.bright]
black = "0x7f7f7f"
blue = "0x5c5cff"
cyan = "0x00ffff"
green = "0x00ff00"
magenta = "0xff00ff"
red = "0xff0000"
white = "0xffffff"
yellow = "0xffff00"

[colors.normal]
black = "0x000000"
blue = "0x268bd2"
cyan = "0x00cdcd"
green = "0x00cd00"
magenta = "0xcd00cd"
red = "0xcd0000"
white = "0xe5e5e5"
yellow = "0xcdcd00"

[colors.primary]
background = "0x111111"
foreground = "0xececec"

[cursor.style]
blinking = "Never"

[env]
TERM = "xterm-256color"

[font]
size = 8.5

[font.normal]
family = "Sauce Code Pro Nerd Font"
style = "Normal"

[shell]
program = "/bin/zsh"

[window]
opacity = 1
